
##
# RLStevenson Theme Options
####

# For baseurl:
# Use '' for / or '/your-dir' for another directory

title:		HJS's Blog
description:	'기술 블로그'
freetext:	'알고리즘 풀이'

baseurl:	'/'
paginate:	3
version:	0.1.0
colorscheme:	scheme-gulfracing

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 url:		https://www.exchangerate-api.com
 name:		'ExchangeRate-API'

github:
 repo:		https://github.com/hjs011/hjs011.github.io

gems:		[jekyll-paginate]

exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']
